# Generated by Django 4.1.6 on 2023-04-07 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField(editable=False, max_length=255)),
                ('categories', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('source', models.URLField(editable=False, max_length=500)),
                ('origin', models.URLField(editable=False, max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('contentType', models.CharField(choices=[('text/markdown', 'markdown'), ('text/plain', 'plain'), ('image/png', 'image/png;base64'), ('image/jpeg', 'image/jpeg;base64')], default='text/plain', max_length=20)),
                ('content', models.TextField(default='')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=20)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(blank=True, default=0)),
                ('commentsSrc', models.CharField(blank=True, default='', max_length=255)),
                ('is_github', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='author.author')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('summary', models.CharField(default='', max_length=100)),
                ('object', models.URLField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='author.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField(editable=False, max_length=500)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('contentType', models.CharField(choices=[('text/markdown', 'markdown'), ('text/plain', 'plain'), ('image/png', 'image/png;base64'), ('image/jpeg', 'image/jpeg;base64')], default='text/plain', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='author.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
