# Generated by Django 4.1.7 on 2023-04-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_unlisted_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.URLField(max_length=500),
        ),
    ]
