# Generated by Django 4.1.7 on 2023-03-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
    ]
