# Generated by Django 4.1.6 on 2023-03-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_github',
            field=models.BooleanField(default=False),
        ),
    ]
