# Generated by Django 4.1.6 on 2023-04-02 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=50)),
                ('profileImage', models.URLField(blank=True, max_length=500)),
                ('url', models.URLField(editable=False, max_length=500)),
                ('host', models.URLField(default='http://127.0.0.1:8000/', editable=False, max_length=500)),
                ('github', models.URLField(blank=True, default='', max_length=500)),
                ('friends', models.ManyToManyField(blank=True, to='author.author')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(default='Node', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('url', models.URLField(default='http://127.0.0.1:8000/', editable=False, max_length=500)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Node',
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='author.author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(default='2', primary_key=True, serialize=False)),
                ('summary', models.CharField(default='', max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='author.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='author.author')),
            ],
        ),
        migrations.AddIndex(
            model_name='inbox',
            index=models.Index(fields=['content_type', 'object_id'], name='author_inbo_content_f0dd76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('actor', 'object')},
        ),
    ]
