# Generated by Django 4.1.6 on 2023-04-02 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.BigAutoField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
