# Generated by Django 4.1.6 on 2023-04-02 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_followrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://sociallydistributed.herokuapp.com/', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.URLField(default='https://sociallydistributed.herokuapp.com/', editable=False, max_length=500),
        ),
    ]
