# Generated by Django 4.1.7 on 2023-04-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_host_alter_node_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://sociallydistributed.herokuapp.com/', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.URLField(default='https://sociallydistributed.herokuapp.com/', editable=False, max_length=500),
        ),
    ]
