# Generated by Django 4.1.6 on 2023-03-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0013_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://sociallydistributed.herokuapp.com/', editable=False, max_length=500),
        ),
    ]
