# Generated by Django 4.1.6 on 2023-03-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0013_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.TextField(blank=True, default=''),
        ),
    ]
