# Generated by Django 4.1.6 on 2023-03-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0014_remove_author_friends_author_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, to='author.author'),
        ),
    ]
