# Generated by Django 4.1.6 on 2023-03-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0014_alter_author_host'),
        ('author', '0015_remove_author_friends_author_friends'),
    ]

    operations = [
    ]
