# Generated by Django 4.1.7 on 2023-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0016_merge_20230328_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.CharField(default={'items': [], 'type': 'followers'}, max_length=500),
        ),
    ]
