# Generated by Django 4.1.5 on 2023-03-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0017_remove_author_friends_author_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='friends',
        ),
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.ManyToManyField(blank=True, to='author.author'),
        ),
    ]
