# Generated by Django 4.1.6 on 2023-04-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0018_remove_author_friends_author_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/', editable=False, max_length=500),
        ),
    ]
